name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install black codespell flake8 isort mypy pytest pyupgrade safety
      - run: black --check . || true
      - run: codespell --ignore-words-list="datas"
      - run: flake8 . --count --exit-zero --select=E9,F63,F7,F82 --show-source --statistics
      - run: flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --show-source --statistics
      - run: isort --check-only --profile black . || true
      - run: pip install -r requirements.txt
      - run: mypy --install-types --non-interactive . || true
      - run: pytest . || true
      - run: pytest --doctest-modules . || true
      - run: python ./loki.py --noprocs --noindicator --dontwait --debug -p ./test
      - run: python ./loki.py --noprocs --noindicator --dontwait --debug --intense -p ./test
      - run: python ./loki.py --noprocs --noindicator --dontwait --debug --csv -p ./test
      - run: shopt -s globstar && pyupgrade --py36-plus **/*.py || true
      - run: safety check
