name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: pip install black codespell mypy pytest ruff safety
      - run: black --check . || true
      - run: codespell --ignore-words-list="datas" --skip="./.git/*"
      - run: ruff --format=github --select=E9,F63,F7,F82 .
      - run: ruff --exit-zero --format=github .
      - run: mypy --install-types --non-interactive . || true
      - run: pip install -r requirements.txt
      - run: pytest . || true
      - run: pytest --doctest-modules . || true
      - run: python ./loki.py --noprocs --noindicator --dontwait --debug -p ./test
      - run: python ./loki.py --noprocs --noindicator --dontwait --debug --intense -p ./test
      - run: python ./loki.py --noprocs --noindicator --dontwait --debug --csv -p ./test
      - run: safety check
